### PR TITLE
Subspace noise removal

### PR DESCRIPTION
**Pull request by ebezzam**
This PR includes work from [this mini-project](https://github.com/GimenaSegrelles/Audio-and-Acoustics-Signal-Processing-Speech-Enhancement-Project) by @GimenaSegrelles and Mathieu Lecoq for the EPFL audio course.

---

Thanks for sending a pull request (PR), we really appreciate that! Before hitting the submit button, we'd be really glad if you could make sure all the following points have been cleared.

Please also refer to the doc on [contributing](https://pyroomacoustics.readthedocs.io/en/pypi-release/contributing.html) for more details. Even if you can't check all the boxes below, do not hesitate to go ahead with the PR and ask for help there.

- [x] Are there docstrings ? Do they follow the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard) style ?
- [ ] Have you run the tests by doing `nosetests` or `py.test` at the root of the repo ?
- [x] Have you checked that the doc builds properly and that any new file has been added to the repo ? How to do that is covered in the [documentation](https://pyroomacoustics.readthedocs.io/en/pypi-release/contributing.html#documentation).
- [x] Is there a unit test for the proposed code modification ? If the PR addresses an issue, the test should make sure the issue is fixed.
- [x] Last but not least, did you document the proposed change in the CHANGELOG file ? It should go under "Unreleased".

Happy PR :smiley:

I ran into an error when running `nosetests` on the DFT unit tests... @fakufaku have you had this?
```
malloc: *** error for object 0x7fddad8f9748: incorrect checksum for freed object - object was probably modified after being freed.
```

### CODE REVIEW

**Comment by fakufaku** [comment]
Pretty cool! I didn't know about the subspace denoising method. I will look at it!

I have been having some issues with nosetests depending on the conda environment used. Sometimes the environment gets corrupted and I get weird errors. I would try to create a fresh environment with only the minimal dependencies of the pyroomacoustics test suite and try running the tests again.

One thing that happen sometimes is that I use a conda env that doesn't have nosetests installed. But if nosetests is installed in the root environment, then the root nosetests is run within the test env, which creates problems. If nosetests is not installed in the test env, installing it might make the problem go away.

Before merging this commit, could you please make sure all the code is properly attributed to the authors (@GimenaSegrelles and Mathieu Lecoq, and yourself where necessary) ? I think we need to add the attribution in comments at the top of the actual file. In addition, I think it would be nice to keep a file with the names of the contributors at the root of the repo. At the moment, it is a bit disparate. We have some names in the files, some names in the README (which should just be the core developers), and some commit information, which is only in git. In this PR, just do this for the added code. We can revisit the rest later.

**Comment by ebezzam** [comment]
Yeah it's an interesting approach working in the time domain!

For the author attributes, you mean like at the top of [this file](https://github.com/LCAV/pyroomacoustics/blob/master/pyroomacoustics/bss/auxiva.py)?

Thanks for the nosetests tip, I'll try this out 🙂

**Comment by ebezzam** [comment]
I did something like the top answer on [this post](https://softwareengineering.stackexchange.com/questions/125836/do-you-have-to-include-a-license-notice-with-every-source-file), using MIT license instead.

**Comment by fakufaku** [comment]
Thanks! But... 🙈 I am just thinking that if we do it this way the boring license stuff will show up on every page of the doc.

It seems a solution is to put the license info *before* the docstring in lines commented with `#` (https://stackoverflow.com/questions/17209712/how-do-i-get-sphinx-to-ignore-the-gpl-notice-in-my-docstring)

```
# Boring
# License
# stuff (c)
'''
The docstring starts here

...
'''
```

**Comment by ebezzam** [comment]
Oops didn't think about it popping up in the docs!

**Comment by fakufaku** [comment]
Thanks, did you check this doesn't show up in a local build of the doc ?

**Comment by ebezzam** [comment]
Yes, it doesn't show up with `#`. I also tried building the doc with the `""" ..."""` comment style and the "boring license stuff" indeed showed up.

**Comment by fakufaku** [comment]
It seems the only mention is as `H. L. Van Trees` in the current code, so all is good. I'll merge this.

**Comment by fakufaku** [comment]
Done, thanks @ebezzam !

**Comment by ebezzam** [comment]
Thanks @fakufaku, and to @GimenaSegrelles and Mathieu Lecoq for their work during the semester!

**Pull request merged**
