### PR TITLE
Adding check for correct absorption coefficients array size for 2D rooms.

### PR DESCRIPTION
**Pull request by CyrilCadoux**
Originally the error was only raised for 3D rooms.

### CODE REVIEW

**Comment by ebezzam** [comment]
@fakufaku, @CyrilCadoux noticed this small problem when digging deeper into the RIR generation part of the package

**Comment by fakufaku** [comment]
@CyrilCadoux Thanks for spotting that! I think we should write more unit tests for the Room class! Just construct a bunch of rooms that span the different options so that we can catch these more easily.

**Comment by fakufaku** [comment]
@CyrilCadoux  This has been merged already, but in the future please also add a note under `bugfix` in the CHANGELOG. I didn't check when I merged, so I added the note now.

**Comment by ebezzam** [comment]
@fakufaku thanks! sorry I forgot to mention the CHANGELOG to Cyril and also forgot it in my PR.

**Pull request merged**
